# Ch. 7 Statistical Intervals Based on a Single Sample {-}

Sections covered: 7.1, 7.2, 7.3

## 7.1 Basic Properties of Confidence Intervals {-}

Skip: "Deriving a Confidence Interval", pp. 282-284; "Bootstrap Confidence Intervals", p. 284

## 7.2 Large-Sample Confidence Intervals for a Population Mean and Proportion {-}

You may use: $\hat{p} \pm z_{\alpha/2} \sqrt{\frac{\hat{p}\hat{q}}{n}}$, rather than the formula (7.10) in the blue box on p. 289 for large sample confidence intervals for proportions, skip p. 290

You may use the method from class $n = \frac{4z^2\hat{p}\hat{q}}{w^2}$ for the minimum $n$ needed to ensure a particular confidence interval width for proportions, rather than formula (7.12) -- both appear on p. 291. As noted in Example 7.9 on p. 291, the easier formula gives a slightly different answer (385 instead of 381).

[Additional material on CI for proportions](https://github.com/jtr13/1201/blob/master/pdfs/LargeSampleCIforPopulationProportion.pdf){target="_blank"}

## 7.3 Intervals Based on a Normal Population Distribution {-}

Skip "A Prediction Interval for a Single Future Value" p. 299 to the end of the section


