# Ch. 3 Discrete Distributions {-}

## 3.3 Expected value {-}

```{r}
x <- 1:5
x
px <- c(.1, .15, .2, .25, .3)
px
x*px
sum(x*px)    # E(X)
```

## 3.3 Variance {-}

```{r}
x - 3.5
(x - 3.5)^2
((x - 3.5)^2)*px
sum(((x - 3.5)^2)*px)   # V(X)
```

## 3.3 Variance (alternative method) {-}
```{r}
x
px
x^2
(x^2)*px
sum((x^2)*px)  # E(X^2)
14-3.5^2     # E(X^2) - [E(X)]^2
```

## 3.4 Binominal Theorem {-}
```{r}
choose(8, 3)    # "8 choose 3"
56*.6^3*.4^5     # P(X = 3) given n = 8, p = .6
```

Direct method
```{r}
dbinom(3, 8, .6)     # P(X = 3) given n = 8, p = .6
```

## 3.5 Hypergeometric {-}

Note that the notation that R uses is different from the Devore textbook:

|parameter|Devore|R|
|---------|------|-|
|total successes|M|m|
|total failures|N-M|n|
|sample size|n|k|
|successes in sample|x|x|

Example (p. 127)

Devore: *h(x; n, M, N)*

*P(X = 2) = h(2; 10, 5, 25)* -->

```{r}
dhyper(x = 2, m = 5, n = 20, k = 10)
```

## 3.6 Poisson {-}

Example (p. 132)

p(3;2) =

```{r}
dpois(3,2)
```

F(3;2) =

```{r}
ppois(3, 2)
```

